-- Migration: Create Promoteurs, Agences, and Projects tables
-- This migration is safe for live sites - it only adds new tables and columns
-- Existing functionality remains unchanged

-- Create Promoteurs table
CREATE TABLE IF NOT EXISTS `promoteurs` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL UNIQUE,
  `slug` varchar(255) NULL UNIQUE,
  `description` text NULL,
  `logo` varchar(500) NULL,
  `website` varchar(500) NULL,
  `phone` varchar(50) NULL,
  `email` varchar(255) NULL,
  `address` varchar(500) NULL,
  `wilaya` varchar(100) NULL,
  `daira` varchar(100) NULL,
  `socialMedia` text NULL,
  `certifications` text NULL,
  `foundedYear` int NOT NULL DEFAULT 0,
  `employeeCount` int NOT NULL DEFAULT 0,
  `totalInvestment` decimal(15,2) NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isFeatured` tinyint(1) NOT NULL DEFAULT 0,
  `viewCount` int NOT NULL DEFAULT 0,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  INDEX `IDX_promoteurs_slug` (`slug`),
  INDEX `IDX_promoteurs_name` (`name`),
  INDEX `IDX_promoteurs_wilaya` (`wilaya`),
  INDEX `IDX_promoteurs_isActive` (`isActive`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create Agences table
CREATE TABLE IF NOT EXISTS `agences` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL UNIQUE,
  `slug` varchar(255) NULL UNIQUE,
  `description` text NULL,
  `logo` varchar(500) NULL,
  `website` varchar(500) NULL,
  `phone` varchar(50) NULL,
  `email` varchar(255) NULL,
  `address` varchar(500) NULL,
  `wilaya` varchar(100) NULL,
  `daira` varchar(100) NULL,
  `socialMedia` text NULL,
  `licenseNumber` varchar(100) NULL,
  `licenseExpiry` date NULL,
  `foundedYear` int NOT NULL DEFAULT 0,
  `agentCount` int NOT NULL DEFAULT 0,
  `specializations` text NULL,
  `serviceAreas` text NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isFeatured` tinyint(1) NOT NULL DEFAULT 0,
  `viewCount` int NOT NULL DEFAULT 0,
  `rating` decimal(3,2) NOT NULL DEFAULT 0,
  `reviewCount` int NOT NULL DEFAULT 0,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  INDEX `IDX_agences_slug` (`slug`),
  INDEX `IDX_agences_name` (`name`),
  INDEX `IDX_agences_wilaya` (`wilaya`),
  INDEX `IDX_agences_isActive` (`isActive`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create Projects table
CREATE TABLE IF NOT EXISTS `projects` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL UNIQUE,
  `slug` varchar(255) NULL UNIQUE,
  `description` text NULL,
  `coverImage` varchar(500) NULL,
  `images` text NULL,
  `location` varchar(255) NULL,
  `wilaya` varchar(100) NULL,
  `daira` varchar(100) NULL,
  `latitude` float NULL,
  `longitude` float NULL,
  `startDate` date NULL,
  `expectedCompletionDate` date NULL,
  `actualCompletionDate` date NULL,
  `status` enum('planning','construction','completed','on_hold','cancelled') NOT NULL DEFAULT 'planning',
  `projectType` enum('residential','commercial','mixed','industrial') NOT NULL DEFAULT 'residential',
  `totalUnits` int NOT NULL DEFAULT 0,
  `availableUnits` int NOT NULL DEFAULT 0,
  `soldUnits` int NOT NULL DEFAULT 0,
  `minPrice` decimal(15,2) NULL,
  `maxPrice` decimal(15,2) NULL,
  `totalBudget` decimal(15,2) NULL,
  `completionPercentage` decimal(5,2) NOT NULL DEFAULT 0,
  `amenities` text NULL,
  `features` text NULL,
  `nearbyPlaces` text NULL,
  `paymentPlans` text NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT 1,
  `isFeatured` tinyint(1) NOT NULL DEFAULT 0,
  `viewCount` int NOT NULL DEFAULT 0,
  `promoteurId` varchar(36) NULL,
  `createdAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  INDEX `IDX_projects_slug` (`slug`),
  INDEX `IDX_projects_status` (`status`),
  INDEX `IDX_projects_wilaya` (`wilaya`),
  INDEX `IDX_projects_promoteurId` (`promoteurId`),
  INDEX `IDX_projects_isActive` (`isActive`),
  INDEX `IDX_projects_projectType` (`projectType`),
  CONSTRAINT `FK_projects_promoteur` FOREIGN KEY (`promoteurId`) REFERENCES `promoteurs` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
